arch: resnet152
epochs: 90
start_epoch: 0
batch_size: 256
lr: 0.1
momentum: 0.9
weight_decay: 1e-4
print_freq: 10
resume: ''
pretrained: false

evaluate: false

workers: 4
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: nccl
seed: null
gpu: null
multiprocessing_distributed: false
dummy: false

distributed: ???

